### ISSUE TITLE
Create base validator for requests

### ISSUE THREAD

**Issue by jdgumz** [devops-golf-s17/wishlists#32]
**As a:** API designer

**I need:** a simple validator

**So that:** I can reliably check input from requests and send safe, clean info to the database layer

**Assumptions:**
- Validation will differ from endpoint to endpoint

**Acceptance Criteria:**
```
A form of validation exists in some minimal form for all endpoints.
```

**Comment by nvme5** [comment]
Removing this issue from this milestone as we will be handling this in the next sprint
