### ISSUE TITLE
Create a new wishlist

### ISSUE THREAD

**Issue by nvme5** [devops-golf-s17/wishlists#4]
**As a** customer/user

**I need** to be able to create new wishlist

**So that** I can add items that I don't have money to purchase to it.

**Assumptions:**
- User doesn't have any wishlist or wishes to create a new one - separate from already existing wishlist
- While creating the wishlist, user has to name the wishlist
- In this, we only create an empty list, not add any items in it
- API Call would be: `POST /wishlists `

**Acceptance Criteria:**
```
When I list all the wishlists (GET /wishlists) 
I should be able to see the wishlist I just created
```
```
When I search for the wishlist I just created
I should be able to see it
```
```
When I create a wishlist without any name
I should get an error that the name parameter is missing
```

**Blocked by:** #2

**Comment by jdgumz** [comment]
LGTM (looks good to me)!

I would add that this is blocked by #2 though.

**Comment by nvme5** [comment]
Ha, that's something I didn't know before, 
and alrighty, updated.

**Comment by nvme5** [comment]
Updated to add the expected URL: `POST /wishlists`
