### ISSUE TITLE
Create unit test case for index resource

### ISSUE THREAD

**Issue by pinocchiochang** [devops-golf-s17/wishlists#46]
**As a** developer

**I need** unit test cases for index method of wishlists.py

**So that** I will be able to run unit test against it.

**Assumptions:**
It will be written in PyUnit syntax
It will reside in test_wishlists.py

**Acceptance Criteria:**
```
Given test cases written in test_wishlists.py
When I run python coverage with the test cases
Then at least 95% of the `index` method will be covered
```

**Comment by palakbhasin** [comment]
Why did you close this?

**Comment by pinocchiochang** [comment]
Because I think you have done this when you create test_wishlists, right?

**Comment by palakbhasin** [comment]
No, index is a separate method. It's ok don't reopen this. It will mess up the burndown. I'll delete this an create a new one

**Comment by pinocchiochang** [comment]
OK. Sorry, my bad.
