### ISSUE TITLE
Add an item to a wishlist

### ISSUE THREAD

**Issue by nvme5** [devops-golf-s17/wishlists#5]
**As a** customer/user

**I need** to add an item to a wishlist

**So that** I can purchase the item whenever I have the money

**Assumptions:**
- Wishlist already exists
- The item is present in the items catalog
- Only the item ID and description is stored, other details can be retrieved based on the item ID if needed
- API Call: `POST /wishlists/<wishlist_id>/items`

**Acceptance Criteria:**
```
When I view the items in the wishlist, 
I see the item I just added
```

**Blocked By:** #2 , #4

**Comment by jdgumz** [comment]
This ticket might also be part of updating a wishlist.

**Comment by nvme5** [comment]
Updated to add the URL - `POST /wishlists/<wishlist_id>/items`
