### ISSUE TITLE
Delete an item from a wishlist

### ISSUE THREAD

**Issue by nvme5** [devops-golf-s17/wishlists#6]
**As a** customer/user

**I need** to delete an item from a wishlist

**So that** I can delete any item I no longer wish to purchase

**Assumptions:**
- Wishlist exists
- Item is present in the wishlist
- API call: `DELETE /wishlists/<wishlist_id>/items/<item_id>`

**Acceptance Criteria:**
```
When I view the items in the wishlist
I no longer see the item I deleted
```

**Blocked by:** #2

**Comment by jdgumz** [comment]
I think this could work well as a specific action on a resource that is outside of the 4 standard operations defined by CRUD.

The URL route would look something like `/wishlists/<id>/actions/remove-item`?  You would send a POST body that specifies the item id/name corresponding to the item to be deleted.

**Comment by jdgumz** [comment]
This ticket might be a part of updating a wishlist.

**Comment by nvme5** [comment]
As discussed, we would implement it using: `DELETE /wishlists/<wishlist_id>/items/<item_id>` 
I've updated the comment for this ticket with the above
