### ISSUE TITLE
Updating wishlist objects.

### ISSUE THREAD

**Issue by xynazog** [devops-golf-s17/wishlists#8]
**As a** Customer

**I need** to update my wishlist objects

**So that** I can change a specific attribute of the object(item in the wishlist)

**Assumptions:**
*Wishlist exists.
*Item is already present in the wishlist.

**Acceptance Criteria:**
```
When I view the items in the wishlist, the attribute is updated with the new URL or the feature being selected by default.
```

**Comment by jdgumz** [comment]
The need for this functionality makes sense, but why not frame it from the perspective of a user?
E.g.,

`As a customer I want to be able to change <stuff> about my wishlist`
